version: '3.8'
services:
  es-data-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: es-data-1
    environment:
      - node.name=es-data-1
      - cluster.name=elk-cluster
      - node.roles=data
      - discovery.seed_hosts= # Master node private ip
      - network.host=0.0.0.0
      - network.publish_host= # This node private ip
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

volumes:
  es-data-1:

networks:
  elk: